name: humaid_soul_ui
description: The cognitive reading interface of HUMAID SOUL.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path_provider: ^2.1.0
  file_picker: ^8.0.0
  syncfusion_flutter_pdfviewer: 24.2.9
  syncfusion_flutter_pdf: 24.2.9
  flutter_tts: ^3.8.0
  http: ^1.2.0
  just_audio: ^0.9.40
  sherpa_onnx: ^1.10.0
  flutter_p2p_connection: ^0.1.0
  bsdiff: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/soul_dict.db.zst
